apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-execution
spec:
  replicas: 1
  selector:
    matchLabels:
      app: code-execution
  template:
    metadata:
      labels:
        app: code-execution
    spec:
      containers:
      - name: code-execution
        image: priyanshptl18/code-exec-base:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            value: "8080"
          - name: SHELL
            value: "/bin/bash"
          - name: HOME
            value: "/home/codeuser"
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"